### ISSUE TITLE
No named parameter with the name 'fileExtension'.

### ISSUE THREAD

**Issue by gisborne** [marchdev-tk/file_selector#3]
## Steps to Reproduce

[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.3 19D76, locale en-US)

1. Run `flutter create bug`.
2. Add to pubspec.yml
3. Use the thing eg in Main.dart: 
`  Widget build(BuildContext context) {
                      FileSelector().pickFile(
                    type: FileType.any
                  ).then((file){
                  });
`
4. Build.
Get:

Compiler message:
/Users/gisborne/dev/bin/flutter/.pub-cache/git/file_selector-25ace36d351eff22c454eaac5aa93861ffdf83ec/lib/src/io/file_selector.mobile.dart:40:7: Error: No named parameter with the name 'fileExtension'.
      fileExtension: type.fileExtensions,
      ^^^^^^^^^^^^^
</details>

**Comment by gisborne** [comment]
Sent you a PR

**Comment by march-dev** [comment]
Merged.

Thank you for the contribution!
